# Alex Sawicki, tul69540 - OS Project 2
# TA: Rachel Lazzaro

myshell: myshell.cpp
	g++ -std=c++11 myshell.cpp -o myshell -Wall -Werror

myshell.o: myshell.cpp
	g++ -c myshell.cpp

clean:
	rm *.o myshell